version: '3'

services:
  zoo1:
    image: 'bitnami/zookeeper:3.4.13-r62'
    hostname: zoo1
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - ./data/zoo1:/bitnami/zookeeper

  kafka1:
    image: 'bitnami/kafka:latest'
    hostname: kafka1
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zoo1:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://:9092
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_HOST_NAME=kafka1
      - KAFKA_ADVERTISED_PORT=9092
    depends_on:
      - zoo1
    volumes:
      - ./data/kafka1:/bitnami/kafka
    ports:
      - 9092:9092

  mysql1:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --sql_mode=""
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: twRuvi2ejllDdA4nnQLa08O
      MYSQL_DATABASE: submissionchecker
    volumes:
      - ./data/mysql1:/var/lib/mysql
    ports:
      - "3306:3306"

  bashenv:
    build: bash
  nodeenv:
    build: node-container

  mysql2:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --sql_mode=""
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: SqfyBWhiFGr7FK60cVR2rel
    volumes:
      - ./data/mysql2:/var/lib/mysql

  ws:
    build: ws
    restart: always
    depends_on:
      - mysql1
      - kafka1
      - zoo1
    ports:
      - "443:443"
    volumes:
      - ./data/upload-dir:/upload-dir
      - ./data/zip-dir:/zip-dir
      - ./data/shared-messages:/shared-messages
      - ./conf/ws:/usr/local/ws/conf
    environment:
      #- KEYSTORE_PATH=file:/usr/local/ws/conf/feedback.p12
      - SERVER_HOST=https://localhost
      - KAFKA_ADDRESS=kafka1:9092
      - MYSQL_URI=jdbc:mysql://mysql1:3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=twRuvi2ejllDdA4nnQLa08O
      - JITSI_URI=https://fk-conf.mni.thm.de/newConf/rooms.php
      - JITSI_SECRET=8Dsupersecurekeydf0
      - JITSI_USER=fbs
      - JWT_SECRET=8Dsupersecurekeydf0
      - BBB_SECRET

  secrettokenchecker:
    build: secrettoken-checker
    depends_on:
      - mysql1
      - kafka1
      - zoo1
      - ws
    environment:
      HOST_UPLOAD_DIR: "${PWD}/data/upload-dir"
      BASH_DOCKER: "thmmniii/bashenv:dev-latest"
      HOST_TMP_DIR: "/tmp/feebi" # Need to be the same folder as mounted to /dockertemp
      KAFKA_ADDRESS: kafka1:9092
    volumes:
      - /var/run/:/var/run/
      - /tmp/feebi:/dockertemp # A temp dir where docker image stores task submissions temporarily
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/shared-messages:/shared-messages
      - ./data/upload-dir:/upload-dir
      - ./conf/secrettoken-checker/ssh:/root/.ssh

  sqlchecker:
    build: sql-checker
    depends_on:
      - mysql2
      - kafka1
      - zoo1
      - ws
    environment:
      KAFKA_ADDRESS: kafka1:9092
      MYSQL_URI: jdbc:mysql://mysql2:3306
      MYSQL_USER: root
      MYSQL_PASSWORD: SqfyBWhiFGr7FK60cVR2rel
    volumes:
      - ./data/upload-dir:/upload-dir
